export interface Report {
  id: string
  type: string
  period: string
  generatedAt: string
  status: "ready" | "generating" | "scheduled"
  size: string | null
  description: string
}

export const reports: Report[] = [
  {
    id: "rpt001",
    type: "Monthly Investor Letter",
    period: "December 2025",
    generatedAt: "Jan 5, 2026",
    status: "ready",
    size: "2.4 MB",
    description: "Monthly performance summary, market commentary, and portfolio updates for investors.",
  },
  {
    id: "rpt002",
    type: "Quarterly Performance Report",
    period: "Q4 2025",
    generatedAt: "Jan 10, 2026",
    status: "ready",
    size: "4.1 MB",
    description: "Comprehensive quarterly analysis including attribution, risk metrics, and outlook.",
  },
  {
    id: "rpt003",
    type: "Risk Report",
    period: "January 2026",
    generatedAt: "Jan 15, 2026",
    status: "generating",
    size: null,
    description: "VaR analysis, stress testing results, and factor exposure breakdown.",
  },
  {
    id: "rpt004",
    type: "Compliance Report",
    period: "Q4 2025",
    generatedAt: "Jan 8, 2026",
    status: "ready",
    size: "1.8 MB",
    description: "Regulatory compliance documentation, trade surveillance, and policy adherence.",
  },
  {
    id: "rpt005",
    type: "Position Report",
    period: "Jan 17, 2026",
    generatedAt: "Jan 17, 2026",
    status: "ready",
    size: "892 KB",
    description: "Daily position snapshot with P&L, exposure, and concentration metrics.",
  },
  {
    id: "rpt006",
    type: "Trade Blotter",
    period: "Jan 17, 2026",
    generatedAt: "Jan 17, 2026",
    status: "ready",
    size: "456 KB",
    description: "Detailed trade log with execution quality analysis and TCA metrics.",
  },
  {
    id: "rpt007",
    type: "Monthly Investor Letter",
    period: "January 2026",
    generatedAt: "Feb 5, 2026",
    status: "scheduled",
    size: null,
    description: "Upcoming monthly letter for January 2026.",
  },
  {
    id: "rpt008",
    type: "ESG Impact Report",
    period: "2025 Annual",
    generatedAt: "Jan 12, 2026",
    status: "ready",
    size: "3.2 MB",
    description: "Annual ESG scoring, carbon footprint analysis, and sustainability metrics.",
  },
  {
    id: "rpt009",
    type: "Quarterly Performance Report",
    period: "Q3 2025",
    generatedAt: "Oct 8, 2025",
    status: "ready",
    size: "3.9 MB",
    description: "Q3 2025 performance analysis with sector attribution and benchmark comparison.",
  },
  {
    id: "rpt010",
    type: "Risk Report",
    period: "December 2025",
    generatedAt: "Dec 31, 2025",
    status: "ready",
    size: "1.5 MB",
    description: "Year-end risk assessment with scenario analysis and tail risk metrics.",
  },
  {
    id: "rpt011",
    type: "Monthly Investor Letter",
    period: "November 2025",
    generatedAt: "Dec 5, 2025",
    status: "ready",
    size: "2.2 MB",
    description: "November performance recap and year-end positioning outlook.",
  },
  {
    id: "rpt012",
    type: "Trade Blotter",
    period: "Jan 16, 2026",
    generatedAt: "Jan 16, 2026",
    status: "ready",
    size: "398 KB",
    description: "Previous day trade execution with slippage and market impact analysis.",
  },
  {
    id: "rpt013",
    type: "Compliance Report",
    period: "Q3 2025",
    generatedAt: "Oct 5, 2025",
    status: "ready",
    size: "1.6 MB",
    description: "Q3 regulatory filings, position limit compliance, and audit trail.",
  },
  {
    id: "rpt014",
    type: "Quarterly Performance Report",
    period: "Q1 2026",
    generatedAt: "Apr 10, 2026",
    status: "scheduled",
    size: null,
    description: "Upcoming Q1 2026 quarterly performance report.",
  },
  {
    id: "rpt015",
    type: "Position Report",
    period: "Jan 16, 2026",
    generatedAt: "Jan 16, 2026",
    status: "ready",
    size: "845 KB",
    description: "End-of-day positions with Greeks, delta exposure, and concentration.",
  },
]

export const reportTypes = [
  { name: "Monthly Investor Letter", desc: "Monthly performance summary and market commentary" },
  { name: "Quarterly Performance", desc: "Comprehensive quarterly analysis with attribution" },
  { name: "Risk Report", desc: "VaR analysis, stress testing, and factor exposure" },
  { name: "Compliance Report", desc: "Regulatory compliance and trade surveillance" },
  { name: "Position Report", desc: "Daily position snapshot with P&L metrics" },
  { name: "Trade Blotter", desc: "Detailed trade log with execution analysis" },
  { name: "ESG Impact Report", desc: "ESG scoring and sustainability metrics" },
]
