export interface ResearchItem {
  id: string
  title: string
  author: string
  agentId: string
  date: string
  tickers: string[]
  category: "Equity" | "Macro" | "Sector"
  summary: string
  conviction: "Strong Buy" | "Buy" | "Hold" | "Sell" | "N/A"
  labels: string[]
}

export const researchItems: ResearchItem[] = [
  {
    id: "r001",
    title: "NVDA Blackwell Architecture Deep Dive",
    author: "Research Agent",
    agentId: "research",
    date: "Jan 18, 2026",
    tickers: ["NVDA"],
    category: "Equity",
    summary: "Comprehensive analysis of Blackwell GPU architecture. Key findings: 2.5x inference throughput vs H100, 25% lower power consumption. Production ramp ahead of schedule with Datacenter revenue guidance likely to increase 15-20%.",
    conviction: "Strong Buy",
    labels: ["AI Generated", "Verified"],
  },
  {
    id: "r002",
    title: "Microsoft Azure AI Services Growth Analysis",
    author: "Research Agent",
    agentId: "research",
    date: "Jan 17, 2026",
    tickers: ["MSFT"],
    category: "Equity",
    summary: "Azure AI services now represent 12% of cloud revenue, up from 8% last quarter. Copilot enterprise adoption exceeds expectations. Maintaining price target of $485 with Strong Buy rating.",
    conviction: "Strong Buy",
    labels: ["AI Generated", "Actionable"],
  },
  {
    id: "r003",
    title: "Semiconductor Supply Chain Update",
    author: "Research Agent",
    agentId: "research",
    date: "Jan 16, 2026",
    tickers: ["TSM", "AVGO", "AMD"],
    category: "Sector",
    summary: "Taiwan Semi capacity expansion on track. Leading-edge node utilization at 95%+. AI chip demand continues to outpace supply. Positive read-through for NVDA, AMD, and fabless designers.",
    conviction: "Buy",
    labels: ["AI Generated"],
  },
  {
    id: "r004",
    title: "Q4 2025 Earnings Preview: Tech Sector",
    author: "Earnings Agent",
    agentId: "earnings",
    date: "Jan 15, 2026",
    tickers: ["NVDA", "MSFT", "GOOGL", "META", "AMZN"],
    category: "Sector",
    summary: "Earnings season preview for mega-cap tech. Expect beats from NVDA (+12% vs consensus) and MSFT (+5%). Watch for GOOGL cloud commentary and META AI capex guidance.",
    conviction: "N/A",
    labels: ["AI Generated", "Verified"],
  },
  {
    id: "r005",
    title: "Federal Reserve Policy Outlook Q1 2026",
    author: "Research Agent",
    agentId: "research",
    date: "Jan 14, 2026",
    tickers: [],
    category: "Macro",
    summary: "Fed likely to hold rates through Q1 despite market pricing in cuts. Inflation remains sticky at 2.8%. Dollar strength may persist, creating headwind for multinationals. Recommend defensive positioning in rate-sensitive sectors.",
    conviction: "N/A",
    labels: ["AI Generated"],
  },
  {
    id: "r006",
    title: "META Reality Labs Strategic Assessment",
    author: "Research Agent",
    agentId: "research",
    date: "Jan 13, 2026",
    tickers: ["META"],
    category: "Equity",
    summary: "Reality Labs losses narrowing faster than expected. Quest 3 adoption strong in enterprise. AI assistant integration driving engagement. Core advertising business remains robust with 22% YoY growth.",
    conviction: "Buy",
    labels: ["AI Generated", "Verified"],
  },
  {
    id: "r007",
    title: "Energy Sector Outlook: OPEC+ Impact Analysis",
    author: "Research Agent",
    agentId: "research",
    date: "Jan 12, 2026",
    tickers: ["XOM", "CVX"],
    category: "Sector",
    summary: "OPEC+ production cuts extended through Q2. Brent crude expected to range $75-85. US majors benefit from operational efficiency gains. Recommend overweight energy for income and inflation hedge.",
    conviction: "Buy",
    labels: ["AI Generated"],
  },
  {
    id: "r008",
    title: "Berkshire Hathaway 13F Analysis",
    author: "SEC Filing Agent",
    agentId: "sec-filing",
    date: "Jan 11, 2026",
    tickers: ["AAPL", "BRK.B"],
    category: "Equity",
    summary: "Berkshire continued reducing AAPL stake, selling 15M shares in Q4. Cash position now exceeds $320B. Possible large acquisition signal or defensive positioning ahead of market uncertainty.",
    conviction: "Hold",
    labels: ["AI Generated", "Verified", "Actionable"],
  },
  {
    id: "r009",
    title: "Amazon AWS and Retail Margin Analysis",
    author: "Research Agent",
    agentId: "research",
    date: "Jan 10, 2026",
    tickers: ["AMZN"],
    category: "Equity",
    summary: "AWS margins expanding as AI workloads grow. Retail segment showing improved efficiency from automation investments. Prime membership growth stabilizing. Target price $225, Buy rating maintained.",
    conviction: "Buy",
    labels: ["AI Generated"],
  },
  {
    id: "r010",
    title: "China Stimulus Impact on EM Exposure",
    author: "Research Agent",
    agentId: "research",
    date: "Jan 9, 2026",
    tickers: [],
    category: "Macro",
    summary: "Recent China stimulus package larger than expected. Positive for commodity demand and EM assets. Consider increasing exposure to copper miners and select EM equities. Risk: geopolitical tensions remain elevated.",
    conviction: "N/A",
    labels: ["AI Generated"],
  },
]
